ERROR 2022-08-10 10:01:21,996: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:01:26,072: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:01:30,149: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:01:34,221: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:02:00,511: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:02:04,570: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:02:08,648: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:02:12,711: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:02:16,774: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:02:20,842: get_twx_connection_status @ line 104 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:06:40,978: _get_twx_connection_status @ line 108 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:06:46,063: _get_twx_connection_status @ line 108 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:06:51,162: _get_twx_connection_status @ line 108 - ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))
ERROR 2022-08-10 10:39:05,450: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A8F219CB20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:32:41,210: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001991E59D8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:32:51,272: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001991E59D300>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:45:34,566: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013D5999D900>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:45:44,770: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013D5999D2A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:45:55,004: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013D5999C250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:46:05,216: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013D5999D1E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:46:15,435: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013D5999D660>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 11:46:25,632: twx_request @ line 93 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013D5999C910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:05:16,171: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BAAF99D120>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:05:26,374: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BAAF99CAF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:05:36,527: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BAAF99CC70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:06:44,733: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017261BA0820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:06:54,774: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017261BA0EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:07:04,863: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017261BA0D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:07:15,046: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017261BA34F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:07:47,975: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A54A9D3F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:08:18,473: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A54A9CD30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:08:28,614: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A54A9D390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:08:38,737: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A54A9F6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:08:48,851: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A54A9C430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
ERROR 2022-08-10 15:08:59,032: twx_request @ line 103 - ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /Thingworx/Things/LocalEms/Properties/isConnected (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A54A9DBA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
